"""Constants for onboarding flow."""
from typing import Final

# ── Retry Configuration ────────────────────────────
MAX_RETRIES: Final[int] = 2
BASE_RETRY_DELAY: Final[float] = 1.0

# ── Circuit Breaker Configuration ──────────────────
CIRCUIT_BREAKER_FAILURE_THRESHOLD: Final[float] = 0.5
CIRCUIT_BREAKER_TIMEOUT: Final[int] = 60
CIRCUIT_BREAKER_MIN_CALLS: Final[int] = 10

# ── Greeting Thresholds ────────────────────────────
SKIN_CONCERN_THRESHOLD: Final[int] = 70

# ── Demo Closet Items ──────────────────────────────
DEMO_CLOSET_ITEMS: Final[list[dict]] = [
    # Jackets (3 items)
    {
        "name": "Navy Wool Blazer",
        "category": "jacket",
        "subcategory": "blazer",
        "color": "navy",
        "color_hex": "#000080",
        "brand": "Theory",
        "price": 495.00,
        "occasions": ["business", "formal"],
        "seasons": ["fall", "winter", "spring"],
        "formality": 0.8,
        "image_url": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400",
    },
    {
        "name": "Black Leather Jacket",
        "category": "jacket",
        "subcategory": "leather",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Mango",
        "price": 149.00,
        "occasions": ["casual", "date"],
        "seasons": ["fall", "winter", "spring"],
        "formality": 0.5,
        "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    },
    {
        "name": "Beige Trench Coat",
        "category": "jacket",
        "subcategory": "trench",
        "color": "beige",
        "color_hex": "#F5F5DC",
        "brand": "Everlane",
        "price": 198.00,
        "occasions": ["business", "casual"],
        "seasons": ["fall", "spring"],
        "formality": 0.7,
        "image_url": "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400",
    },
    # Dresses (2 items)
    {
        "name": "Black Midi Dress",
        "category": "dress",
        "subcategory": "midi",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Reformation",
        "price": 98.00,
        "occasions": ["date", "formal"],
        "seasons": ["spring", "summer", "fall"],
        "formality": 0.7,
        "image_url": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
    },
    {
        "name": "White Linen Midi Dress",
        "category": "dress",
        "subcategory": "midi",
        "color": "white",
        "color_hex": "#FFFFFF",
        "brand": "Zara",
        "price": 49.00,
        "occasions": ["casual", "date"],
        "seasons": ["spring", "summer"],
        "formality": 0.3,
        "image_url": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400",
    },
    # Tops (3 items)
    {
        "name": "Cream Silk Blouse",
        "category": "top",
        "subcategory": "blouse",
        "color": "cream",
        "color_hex": "#FFFDD0",
        "brand": "Madewell",
        "price": 88.00,
        "occasions": ["business", "casual"],
        "seasons": ["spring", "summer", "fall"],
        "formality": 0.6,
        "image_url": "https://images.unsplash.com/photo-1564257577-4f0b4c8c1e5f?w=400",
    },
    {
        "name": "Grey Cashmere Sweater",
        "category": "top",
        "subcategory": "sweater",
        "color": "grey",
        "color_hex": "#808080",
        "brand": "COS",
        "price": 125.00,
        "occasions": ["casual", "business"],
        "seasons": ["fall", "winter"],
        "formality": 0.5,
        "image_url": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
    },
    {
        "name": "Black Cotton Turtleneck",
        "category": "top",
        "subcategory": "turtleneck",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Uniqlo",
        "price": 29.00,
        "occasions": ["casual", "business"],
        "seasons": ["fall", "winter"],
        "formality": 0.5,
        "image_url": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400",
    },
    # Bottoms (3 items)
    {
        "name": "Dark Wash Jeans",
        "category": "bottom",
        "subcategory": "jeans",
        "color": "blue",
        "color_hex": "#1E3A8A",
        "brand": "Levi's",
        "price": 98.00,
        "occasions": ["casual"],
        "seasons": ["spring", "summer", "fall", "winter"],
        "formality": 0.3,
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
    },
    {
        "name": "Black Wool Trousers",
        "category": "bottom",
        "subcategory": "trousers",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Aritzia",
        "price": 148.00,
        "occasions": ["business", "formal"],
        "seasons": ["fall", "winter", "spring"],
        "formality": 0.8,
        "image_url": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
    },
    {
        "name": "Beige Linen Pants",
        "category": "bottom",
        "subcategory": "pants",
        "color": "beige",
        "color_hex": "#F5F5DC",
        "brand": "Everlane",
        "price": 78.00,
        "occasions": ["casual"],
        "seasons": ["spring", "summer"],
        "formality": 0.4,
        "image_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400",
    },
    # Shoes (2 items)
    {
        "name": "Black Heels",
        "category": "shoes",
        "subcategory": "heels",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Sam Edelman",
        "price": 120.00,
        "occasions": ["business", "formal", "date"],
        "seasons": ["spring", "summer", "fall", "winter"],
        "formality": 0.8,
        "image_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400",
    },
    {
        "name": "White Sneakers",
        "category": "shoes",
        "subcategory": "sneakers",
        "color": "white",
        "color_hex": "#FFFFFF",
        "brand": "Veja",
        "price": 150.00,
        "occasions": ["casual"],
        "seasons": ["spring", "summer", "fall"],
        "formality": 0.2,
        "image_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
    },
    # Accessories (2 items)
    {
        "name": "Gold Hoop Earrings",
        "category": "accessory",
        "subcategory": "earrings",
        "color": "gold",
        "color_hex": "#FFD700",
        "brand": "Mejuri",
        "price": 29.00,
        "occasions": ["casual", "business", "date"],
        "seasons": ["spring", "summer", "fall", "winter"],
        "formality": 0.5,
        "image_url": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
    },
    {
        "name": "Black Leather Tote",
        "category": "accessory",
        "subcategory": "bag",
        "color": "black",
        "color_hex": "#000000",
        "brand": "Cuyana",
        "price": 195.00,
        "occasions": ["business", "casual"],
        "seasons": ["spring", "summer", "fall", "winter"],
        "formality": 0.6,
        "image_url": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400",
    },
]

# ── Skin Concern Labels ────────────────────────────
SKIN_CONCERNS: Final[dict[str, str]] = {
    "moisture": "dry skin",
    "acne": "breakouts",
    "wrinkles": "fine lines",
    "pores": "enlarged pores",
    "dark_circles": "dark circles",
}
